export const API_CALL_ERROR = 'API_CALL_ERROR';
export const SET_MENU_ID = 'SET_MENU_ID';
export const FETCH_MENU_REQUESTED = 'FETCH_MENU_REQUESTED';
export const FETCH_MENU_SUCCESSED = 'FETCH_MENU_SUCCESSED';
export const SORT_MENU = 'SORT_MENU';
export const SAVE_MENU_REQUESTED = 'SAVE_MENU_REQUESTED';
export const SAVE_MENU_SUCCESSED = 'SAVE_MENU_SUCCESSED';